/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d2d9f4",
        "on-primary": "#ffffff",
        "on-background": "#131b2e",
        "inverse-surface": "#283044",
        "surface-tint": "#2e647c",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#7f2b00",
        "primary-fixed": "#bfe8ff",
        "inverse-on-surface": "#eef0ff",
        "surface-container-low": "#f2f3ff",
        "on-primary-container": "#89bdd8",
        "tertiary-fixed": "#7ffc97",
        "on-secondary-container": "#571a00",
        "on-primary-fixed-variant": "#0d4d63",
        "secondary-container": "#fd651e",
        "error": "#ba1a1a",
        "secondary": "#a73a00",
        "primary": "#003548",
        "surface-container": "#eaedff",
        "on-tertiary-fixed": "#002109",
        "primary-fixed-dim": "#99cee9",
        "tertiary-fixed-dim": "#62df7d",
        "on-surface": "#131b2e",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#005320",
        "on-primary-fixed": "#001f2b",
        "surface-container-high": "#e2e7ff",
        "surface-variant": "#dae2fd",
        "secondary-fixed": "#ffdbce",
        "primary-container": "#0e4d64",
        "on-surface-variant": "#40484c",
        "tertiary": "#003914",
        "surface-container-highest": "#dae2fd",
        "secondary-fixed-dim": "#ffb599",
        "outline": "#71787d",
        "on-secondary-fixed": "#370e00",
        "surface": "#faf8ff",
        "tertiary-container": "#005321",
        "background": "#faf8ff",
        "outline-variant": "#c0c7cd",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#faf8ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#4fcd6e",
        "inverse-primary": "#99cee9"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "max-content-width": "1240px",
        "space-12": "3rem",
        "space-6": "1.5rem",
        "space-2": "0.5rem",
        "space-8": "2rem",
        "space-16": "4rem",
        "space-1": "0.25rem",
        "space-4": "1rem",
        "margin-mobile": "1rem",
        "space-3": "0.75rem",
        "gutter-mobile": "1rem",
        "margin-desktop": "2rem",
        "gutter-desktop": "1.5rem"
      },
      fontFamily: {
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "display": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "title-md": ["'Plus Jakarta Sans'", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "letterSpacing": "0", "fontWeight": "400" }],
        "headline-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "700" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "display": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.03em", "fontWeight": "800" }],
        "body-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "title-md": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.005em", "fontWeight": "600" }]
      }
    }
  },
  plugins: []
}
